import '../globals.css';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import SideNav from '@/components/side-nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Side Navigation',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-white${inter.className}`}>
        <SideNav />
        {children}
      </body>
    </html>
  );
}
