export const drawerContent = {
  menu: {
    id: 'gid://shopify/Menu/158480367776',
    title: 'Footer menu',
    items: [
      {
        id: 'gid://shopify/MenuItem/481493778690',
        title: 'Refund policy',
        url: 'https://campussutra.com/pages/shipping-and-return-policies',
        type: 'PAGE',
        items: [
          {
            id: 'gid://shopify/MenuItem/481493778690',
            title: 'Refund policy',
            url: 'https://campussutra.com/pages/shipping-and-return-policies',
            type: 'PAGE',
            items: [],
          },
          {
            id: 'gid://shopify/MenuItem/481493778690',
            title: 'Refund policy',
            url: 'https://campussutra.com/pages/shipping-and-return-policies',
            type: 'PAGE',
            items: [],
          },
          {
            id: 'gid://shopify/MenuItem/481493778690',
            title: 'Refund policy',
            url: 'https://campussutra.com/pages/shipping-and-return-policies',
            type: 'PAGE',
            items: [],
          },
          {
            id: 'gid://shopify/MenuItem/481493778690',
            title: 'Refund policy',
            url: 'https://campussutra.com/pages/shipping-and-return-policies',
            type: 'PAGE',
            items: [],
          },
        ],
      },
      {
        id: 'gid://shopify/MenuItem/481493614850',
        title: 'Shipping Policy',
        url: 'https://campussutra.com/policies/shipping-policy',
        type: 'SHOP_POLICY',
        items: [],
      },
      {
        id: 'gid://shopify/MenuItem/481493647618',
        title: 'Terms of Service',
        url: 'https://campussutra.com/policies/terms-of-service',
        type: 'SHOP_POLICY',
        items: [],
      },
      {
        id: 'gid://shopify/MenuItem/481493680386',
        title: 'Return your order ',
        url: 'https://campussutra.com/a/returns',
        type: 'HTTP',
        items: [],
      },
      {
        id: 'gid://shopify/MenuItem/481493713154',
        title: 'Privacy Policy',
        url: 'https://campussutra.com/pages/privacy-policy-1',
        type: 'HTTP',
        items: [],
      },
      {
        id: 'gid://shopify/MenuItem/481493745922',
        title: 'Blog',
        url: 'https://cdn.shopify.com/s/files/1/0457/8246/6720/files/4_CAMPUS_SUTRA_JACKETS_TO_COVER_EVERY_SITUATION_1.pdf?v=1644481842',
        type: 'HTTP',
        items: [],
      },
      {
        id: 'gid://shopify/MenuItem/486042566914',
        title: 'Sitemap',
        url: 'https://campussutra.com/sitemap',
        type: 'HTTP',
        items: [],
      },
    ],
  },
};
